[package]
name = "brainfuck-rs"
version = "0.1.0"
authors = ["Artem Pyatnitskiy <avpyatn1@mts.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
